language: node_js

sudo: false

node_js:
  - "8"
  - "7"

install:
  - yarn

script:
  - yarn test

notifications:
  email: false

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
